apiVersion: v1
kind: PersistentVolume
metadata:
  name: plex-library-nfs-pv
  labels:
    app: plex-library
spec:
  capacity:
    storage: {{ .Values.nfs.libraryStorageSize }}
  accessModes:
    - ReadOnlyMany
  nfs:
    server: {{ .Values.nfs.serverIp }}
    path: "{{ .Values.nfs.libraryPath }}"
  persistentVolumeReclaimPolicy: Retain # "Delete" would not be used for NFS

---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: plex-config-nfs-pv
  labels:
    app: plex-config
spec:
  capacity:
    storage: {{ .Values.nfs.configStorageSize }}
  accessModes:
    - ReadWriteOnce
  nfs:
    server: {{ .Values.nfs.serverIp }}
    path: "{{ .Values.nfs.configPath }}"
  persistentVolumeReclaimPolicy: Retain