apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.name }}
  namespace: {{ .Values.namespace }}
spec:
  type: {{ .Values.service.type }}
  selector:
    {{- with .Values.podLabels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  ports:
    - port: {{ .Values.port }}        # Internal port for the service
      targetPort: {{ .Values.port }}  # Port where the Plex container is listening
  #    nodePort: {{ .Values.port }}    # NodePort to expose the service