apiVersion: v1
kind: Service
metadata:
  name: cloudflared
  namespace: {{ .Values.namespace }}
spec:
  type: LoadBalancer
  selector:
    app: cloudflared
  ports:
    - name: http
      port: 80
      targetPort: 80
    - name: https
      port: 443
      targetPort: 443